### ISSUE TITLE
목록페이지 부가기능 버튼 추가(레이아웃 선택, 편집 아이콘)

### ISSUE THREAD

**Issue by KimEunA97** [kongukjae/KDT-2-Project-C-10#4]
@kongukjae
피그마에 디자인 추가해놨어요. 확인하신 후에 버튼 두개 추가해주세용

**Comment by kongukjae** [comment]
알겠습니다!

**Comment by KimEunA97** [comment]
어라 두개가 아니라 세개 같네요~ 부탁드립니다~

**Comment by kongukjae** [comment]
`      `
      
     작업진행 간 팀장님의 diff 검토를 위해 주요부분은 issue4 라는 주석으로 찾을 수 있도록 진행하였습니다.
     확인 부탁드리겠습니다.

**Comment by KimEunA97** [comment]
코드 확인 했습니다. position 값이 fixed가 아니라 sticky로 되어있는데 다시 한번 확인 해주시겠어요~

**Comment by KimEunA97** [comment]
확인 했습니다~
